import { create } from 'zustand'
import * as audio from '../services/audioPlayer'
import { getRandomRemix, addToHistory, upsertRemixes } from '../services/database'
import type { Remix, RepeatMode, ShuffleMode, CatalogFilters } from '../types'

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isPlaceholderUrl(url?: string): boolean {
  // Placeholder: generated by buildMp3Url → "OCRxxxxx.mp3" with no descriptive filename
  return !!url?.match(/\/OCR\d{5}\.mp3$/)
}

// Race-condition guard: each play request gets a unique token.
// If a newer request comes in before this one resolves, abandon this one.
let _playToken = 0

async function resolveRemixDetail(remix: Remix): Promise<Remix> {
  if (!isPlaceholderUrl(remix.mp3Url)) return remix

  try {
    const { fetchRemixDetail } = await import('../api/ocremix')
    const detail    = await fetchRemixDetail(remix.id)
    const enriched  = { ...remix, ...detail } as Remix

    if (!isPlaceholderUrl(enriched.mp3Url)) {
      // Got a real URL — persist it so we don't scrape again
      await upsertRemixes([enriched])
      console.log('[Player] Resolved:', enriched.id, '→', enriched.mp3Url)
      return enriched
    }

    console.warn('[Player] Detail fetch still returned placeholder for', remix.id,
      '— page may load URL dynamically. Using placeholder.')
    return remix
  } catch (err) {
    console.warn('[Player] Detail fetch failed for', remix.id, err)
    return remix
  }
}

// ─── Store interface ─────────────────────────────────────────────────────────

interface PlayerStore {
  currentRemix:    Remix | null
  queue:           Remix[]
  queueIndex:      number
  isPlaying:       boolean
  isLoadingDetail: boolean
  repeatMode:      RepeatMode
  shuffleMode:     ShuffleMode
  rouletteFilters: CatalogFilters
  volume:          number

  playRemix:          (remix: Remix, queue?: Remix[]) => Promise<void>
  playQueue:          (remixes: Remix[], index?: number) => Promise<void>
  resume:             () => void
  pause:              () => void
  skipToNext:         () => Promise<void>
  skipToPrevious:     () => Promise<void>
  spinRoulette:       (filtered?: boolean) => Promise<void>
  setRepeatMode:      (mode: RepeatMode) => void
  setShuffleMode:     (mode: ShuffleMode) => void
  setRouletteFilters: (f: CatalogFilters) => void
  setVolume:          (v: number) => void
  addToQueue:         (remix: Remix) => void
  _setIsPlaying:      (v: boolean) => void
}

export const usePlayerStore = create<PlayerStore>((set, get) => {
  audio.on('play',  () => get()._setIsPlaying(true))
  audio.on('pause', () => get()._setIsPlaying(false))
  audio.on('stop',  () => get()._setIsPlaying(false))
  audio.on('end',   () => {
    if (get().repeatMode === 'track') { audio.seek(0); audio.play() }
    else get().skipToNext()
  })

  audio.wireMediaActions({
    play:  () => { audio.play();  get()._setIsPlaying(true) },
    pause: () => { audio.pause(); get()._setIsPlaying(false) },
    next:  () => get().skipToNext(),
    prev:  () => get().skipToPrevious(),
    seek:  (d) => { if (d.seekTime != null) audio.seek(d.seekTime) },
  })

  return {
    currentRemix:    null,
    queue:           [],
    queueIndex:      0,
    isPlaying:       false,
    isLoadingDetail: false,
    repeatMode:      'off',
    shuffleMode:     'off',
    rouletteFilters: {},
    volume:          1,

    playRemix: async (remix, queue) => {
      const token = ++_playToken
      set({ isLoadingDetail: isPlaceholderUrl(remix.mp3Url) })

      const resolved = await resolveRemixDetail(remix)

      // Stale request — user already clicked something else
      if (token !== _playToken) return

      const q             = queue ?? [resolved]
      const index         = Math.max(0, q.findIndex(r => r.id === resolved.id))
      const resolvedQueue = q.map(r => r.id === resolved.id ? resolved : r)

      audio.setQueue(resolvedQueue, index)
      set({ isLoadingDetail: false })

      try {
        await audio.loadAndPlay(resolved)
      } catch (err) {
        console.error('[Player] Playback error:', err)
        set({ isLoadingDetail: false })
        return
      }

      if (token !== _playToken) return  // check again after async loadAndPlay
      set({ currentRemix: resolved, queue: resolvedQueue, queueIndex: index })
      await addToHistory(resolved.id)
    },

    playQueue: async (remixes, index = 0) => {
      const token = ++_playToken
      const remix = remixes[index]
      if (!remix) return

      set({ isLoadingDetail: isPlaceholderUrl(remix.mp3Url) })
      const resolved      = await resolveRemixDetail(remix)
      if (token !== _playToken) return

      const resolvedQueue = remixes.map(r => r.id === resolved.id ? resolved : r)
      audio.setQueue(resolvedQueue, index)
      set({ isLoadingDetail: false })

      try {
        await audio.loadAndPlay(resolved)
      } catch (err) {
        console.error('[Player] Playback error:', err)
        return
      }

      if (token !== _playToken) return
      set({ currentRemix: resolved, queue: resolvedQueue, queueIndex: index })
      await addToHistory(resolved.id)
    },

    resume: () => { audio.play(); set({ isPlaying: true }) },
    pause:  () => { audio.pause(); set({ isPlaying: false }) },

    skipToNext: async () => {
      const { queue, queueIndex, repeatMode, shuffleMode } = get()
      if (!queue.length) return

      let nextIndex: number
      if (shuffleMode === 'on') {
        nextIndex = Math.floor(Math.random() * queue.length)
      } else {
        nextIndex = queueIndex + 1
        if (nextIndex >= queue.length) {
          if (repeatMode === 'queue') nextIndex = 0
          else return
        }
      }

      const next = queue[nextIndex]
      if (!next) return

      const token    = ++_playToken
      set({ isLoadingDetail: isPlaceholderUrl(next.mp3Url) })
      const resolved = await resolveRemixDetail(next)
      if (token !== _playToken) return
      set({ isLoadingDetail: false })

      try {
        await audio.loadAndPlay(resolved)
        set({ currentRemix: resolved, queueIndex: nextIndex })
        await addToHistory(resolved.id)
      } catch { /* skip to next on error */ }
    },

    skipToPrevious: async () => {
      if (audio.getPosition() > 3) { audio.seek(0); return }
      const { queue, queueIndex } = get()
      const prev = queue[Math.max(0, queueIndex - 1)]
      if (!prev) return

      const token    = ++_playToken
      set({ isLoadingDetail: isPlaceholderUrl(prev.mp3Url) })
      const resolved = await resolveRemixDetail(prev)
      if (token !== _playToken) return
      set({ isLoadingDetail: false })

      try {
        await audio.loadAndPlay(resolved)
        set({ currentRemix: resolved, queueIndex: Math.max(0, queueIndex - 1) })
      } catch { /* ignore */ }
    },

    spinRoulette: async (filtered = false) => {
      const remix = await getRandomRemix(filtered ? get().rouletteFilters : undefined)
      if (!remix) return
      await get().playRemix(remix)
    },

    setRepeatMode:      (repeatMode)      => set({ repeatMode }),
    setShuffleMode:     (shuffleMode)     => set({ shuffleMode }),
    setRouletteFilters: (rouletteFilters) => set({ rouletteFilters }),
    setVolume:          (volume)          => { audio.setVolume(volume); set({ volume }) },
    addToQueue:         (remix)           => set(s => ({ queue: [...s.queue, remix] })),
    _setIsPlaying:      (isPlaying)       => set({ isPlaying }),
  }
})
